LogAppWebCore/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using LogAppWebCore.Data;
using LogAppWebCore.Models;
using LogAppWebCore.Models.UserViewModels;
using LogAppWebCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Net.Http.Headers;

namespace LogAppWebCore.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;

        public UsersController(UserManager<User> userManager, RoleManager<Role> roleManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [Authorize(Policy = "UsersView" )]
        public async Task<IActionResult> Index(string statusMessage)
        {
            var userList = await _userManager.Users.Where(u => !u.UserName.Equals("admin", StringComparison.CurrentCultureIgnoreCase)).ToListAsync();

            var users = userList.Select(o => new UserEditViewModel
                {
                    Id = o.Id,
                    Name = o.Name,
                    Surname = o.Surname,
                    UserName = o.Surname,
                })
                .ToList();

            var model = new UserListViewModel
            {
                StatusMessage = statusMessage,
                Users = users
            };

            return View(model);
        }

        [Authorize(Policy = "UsersView")]
        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.Users.Include(o => o.Roles).ThenInclude(o => o.Role).FirstOrDefaultAsync(u => u.Id == id);

            if (user == null)
                return RedirectToAction("Index");

            var roleNames = user.Roles.Select(o => o.Role.Name);
            var roles = String.Join(", ", roleNames);

            var model = new UserDetailsViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                UserName = user.UserName,
                Email = user.Email,
                Active = user.Active,
                Roles = roles
            };

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "UsersCreate")]
        public async Task<IActionResult> Create()
        {
            var applicationRoles = await _roleManager.Roles.ToListAsync();

            var roles = applicationRoles.Select(applicationRole => new RoleViewModel
                {
                    Id = applicationRole.Id,
                    Name = applicationRole.Name
                })
                .ToList();

            var model = new UserEditViewModel
            {
                Roles = roles
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "UsersCreate")]
        public async Task<IActionResult> Create(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }

            var newUser = new User
            {
                Name = model.Name,
                Surname = model.Surname,
                UserName = model.UserName,
                Email = model.Email,
                Active = true,
                ChangePassword = true
            };
            var password = PasswordGenerator.GenerateRandomPassword();

            var result = await _userManager.CreateAsync(newUser, password);

            if (result.Succeeded)
            {
                foreach (var role in model.Roles.Where(role => role.IsSelected))
                    await _userManager.AddToRoleAsync(newUser, role.Name);

                model.StatusMessage = $"User created successfully with password: {password}";
                return View(model);
            }

            AddErrors(result);
            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "UsersEdit")]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id);

            if (user == null)
                return RedirectToAction("Index");

            var roleViewModelList = new List<RoleViewModel>();
            var applicationRoles = await _roleManager.Roles.ToListAsync();

            foreach (var applicationRole in applicationRoles)
            {
                roleViewModelList.Add(new RoleViewModel
                {
                    Id = applicationRole.Id,
                    Name = applicationRole.Name,
                    IsSelected = await _userManager.IsInRoleAsync(user, applicationRole.Name)
                });
            }

            var model = new UserEditViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                UserName = user.UserName,
                Email = user.Email,
                Active = user.Active,
                Roles = roleViewModelList
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "UsersEdit")]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit");
            }

            var user = await _userManager.Users.FirstOrDefaultAsync(o => o.Id == model.Id);

            user.Name = model.Name;
            user.Surname = model.Surname;
            user.UserName = model.UserName;
            user.Email = model.Email;
            user.Active = model.Active;

            foreach (var role in model.Roles)
            {
                if (role.IsSelected)
                    await _userManager.AddToRoleAsync(user, role.Name);
                else
                    await _userManager.RemoveFromRoleAsync(user, role.Name);
            }

            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                model.StatusMessage = "User updated successfully.";

                if (!model.Active)
                    await _userManager.UpdateSecurityStampAsync(user);

                return View(model);
            }

            AddErrors(result);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "UsersDelete")]
        public async Task<IActionResult> Delete(int id)
        {
            var userToDelete = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id);
            await _userManager.DeleteAsync(userToDelete);

            return RedirectToAction("Index", new {StatusMessage = "User deleted succesfully."});
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

LogAppWebCore/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LogAppWebCore.Models;
using LogAppWebCore.Models.WorkerViewModels;
using LogAppWebCore.Models.WorkLogViewModels;
using LogAppWebCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LogAppWebCore.Controllers
{
    [Authorize(Policy = "IsWorker")]
    public class WorkerController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly WorkLogService _workLogService;

        public WorkerController(UserManager<User> userManager, WorkLogService workLogService)
        {
            _userManager = userManager;
            _workLogService = workLogService;
        }

        public IActionResult Index()
        {
            return View("Index");
        }

        public async Task<IActionResult> WorkLogs()
        {
            var user = await _userManager.Users.Include(o => o.WorkLogs)
                .FirstOrDefaultAsync(o => o.UserName == User.Identity.Name);

            var index = 1;
            var workLogsVm = user.WorkLogs.Select(o => new WorkerWorkLogViewModel
            {
                Number = index++,
                Id = o.Id,
                WorkDate = o.WorkStartTime.ToString("d"),
                WorkStartTime = o.WorkStartTime.ToString("t"),
                WorkEndTime = o.WorkEndTime.ToString("t"),
                WorkDuration = o.WorkDuration.ToString(@"hh\:mm")
            })
            .ToList();

            var model = new WorkerWorkLogListViewModel
            {
                WorkLogs = workLogsVm
            };

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> WorkLogDetails(int id)
        {
            var user = await _userManager.Users.Include(o => o.WorkLogs)
                .FirstOrDefaultAsync(o => o.UserName == User.Identity.Name);

            if (user == null)
                return RedirectToAction("WorkLogs");

            var workLog = user.WorkLogs.FirstOrDefault(o => o.Id == id);

            if (workLog == null)
                return RedirectToAction("WorkLogs");

            var model = new WorkerWorkLogViewModel
            {
                WorkDate = workLog.WorkStartTime.ToString("d"),
                WorkStartTime = workLog.WorkStartTime.ToString("t"),
                WorkEndTime = workLog.WorkEndTime.ToString("t"),
                WorkDuration = workLog.WorkDuration.ToString(@"hh\:mm")
            };

            return View(model);
        }
    }
}

LogAppWebCore/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LogAppWebCore.Models;
using LogAppWebCore.Models.WorkersViewModels;
using LogAppWebCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LogAppWebCore.Controllers
{
    [Authorize]
    public class WorkersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly WorkLogService _workLogService;
        private readonly WorkerService _managerService;

        public WorkersController(UserManager<User> userManager, WorkLogService workLogService, WorkerService managerService)
        {
            _userManager = userManager;
            _workLogService = workLogService;
            _managerService = managerService;
        }

        [Authorize(Policy = "WorkersView")]
        public IActionResult Index()
        {
            var workers = _managerService.GetWorkers();

            var workerListViewModel = workers.Select(o => new WorkerDetailsViewModel
            {
                Id = o.Id,
                Name = o.Name,
                Surname = o.Surname,
            })
            .ToList();

            var model = new WorkerListViewModel
            {
                Workers = workerListViewModel
            };

            return View(model);
        }

        [Authorize(Policy = "WorkersView")]
        public async Task<IActionResult> Details(int workerId)
        {
            var worker = await _userManager.Users.SingleOrDefaultAsync(u => u.Id == workerId);

            if (worker == null)
                return RedirectToAction("Index");

            var model = new WorkerDetailsViewModel
            {
                Name = worker.Name,
                Surname = worker.Surname,
                Email = worker.Email,
            };

            return View(model);
        }

        /*
        public IActionResult WorkerWorkLogs(int workerId)
        {
            var user = _userManager.Users.SingleOrDefault(o => o.Id == workerId);
            var workLogs = _workLogService.GetUserWorkLogsWithUser(user);

            var workLogListViewModel = workLogs.Select(o => new WorkLogViewModel
                {
                    UserName = o.User.Name,
                    UserSurname = o.User.Surname,
                    WorkDate = o.WorkStartTime.ToString("d"),
                    WorkStartTime = o.WorkStartTime.ToString("t"),
                    WorkEndTime = o.WorkEndTime.ToString("t"),
                    WorkDuration = o.WorkDuration.ToString(@"hh\:mm")
                })
                .ToList();

            var model = new WorkLogListViewModel
            {
                WorkLogs = workLogListViewModel
            };

            return View(model);
        }

        public IActionResult WorkerWorkLogDetails(int workLogId)
        {
            var workLog = _workLogService.GetWorkLogWithUser(workLogId);

            if (workLog == null)
                return RedirectToAction("Index");

            var model = new WorkLogViewModel
            {
                UserName = workLog.User.Name,
                UserSurname = workLog.User.Surname,
                WorkDate = workLog.WorkStartTime.ToString("d"),
                WorkStartTime = workLog.WorkStartTime.ToString("t"),
                WorkEndTime = workLog.WorkEndTime.ToString("t"),
                WorkDuration = workLog.WorkDuration.ToString(@"hh\:mm")
            };

            return View(model);
        }
        */
    }
}

LogAppWebCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogAppWebCore</title>
    <link href="~/master.min.css" rel="stylesheet"/>
    <link href="~/css/style.css" rel="stylesheet"/>
    <script src="~/master.min.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row justify-content-around">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="col-12 p-0 m-0 position-sticky" style="top: 0; z-index: 999">
                    @await Html.PartialAsync("_TopNavBar")
                </div>

                <div class="col-md-2 col-12 p-0 m-0 position-sticky" style="top: 56px; z-index: 998">
                    @await Html.PartialAsync("_SideNavBar")
                </div>
            }
            <div class="col-md-10 col-12 p-0 py-2 main-content">
                @RenderBody()
            </div>
        </div>
    </div>

</body>
</html>

LogAppWebCore/Views/Shared/_NavBarsSharedLinks.cshtml
<ul class="flex-md-column navbar-nav w-100 justify-content-between">

    <li class="nav-item w-100">
        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle nav-link pl-0"><i class="fa fa-heart-o fa-fw"></i> <span class="">Home</span></a>
        <ul class="collapse" id="homeSubmenu">
            <li>
                <a class="nav-link" href="#">Home 1</a>
            </li>
            <li>
                <a class="nav-link" href="#">Home 2</a>
            </li>
            <li>
                <a class="nav-link" href="#">Home 3</a>
            </li>
        </ul>
    </li>

    <li class="nav-item w-100">
        <a class="nav-link pl-0" href="#"><i class="fa fa-heart-o fa-fw"></i> <span class="">Link</span></a>
    </li>
    <li class="nav-item w-100">
        <a class="nav-link pl-0" href="#"><i class="fa fa-book fa-fw"></i> <span class="">Link</span></a>
    </li>
    <li class="nav-item w-100">
        <a class="nav-link pl-0" href="#"><i class="fa fa-heart fa-fw"></i> <span class="">Link</span></a>
    </li>
    <li class="nav-item w-100">
        <a class="nav-link pl-0" href="#"><i class="fa fa-star fa-fw"></i> <span class="">Link</span></a>
    </li>
    <li class="nav-item w-100">
        <a class="nav-link pl-0" href="#"><i class="fa fa-list fa-fw"></i> <span class="">Link</span></a>
    </li>
</ul>

LogAppWebCore/Views/Shared/_SideNavBar.cshtml
<div class="h-100 bg-dark d-sm-block d-none">
    <nav class="navbar navbar-expand-sm navbar-dark align-items-start position-sticky py-md-0 sidebar">

        <ul class="flex-md-column navbar-nav w-100 justify-content-between">
            
        <!--
        <li class="nav-item w-100">
            <a href="#submenu1Side" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle nav-link pl-0"><i class="fa fa-heart-o fa-fw"></i> <span class="">Home</span></a>
            <ul class="collapse list-unstyled" id="submenu1Side">
                <li>
                    <a class="nav-link" href="#">Home 1</a>
                </li>
                <li>
                    <a class="nav-link" href="#">Home 2</a>
                </li>
                <li>
                    <a class="nav-link" href="#">Home 3</a>
                </li>
            </ul>
        </li>
        -->

            <li class="nav-item w-100">
                <a asp-controller="Users" asp-action="Index" class="nav-link pl-0"><i class="fa fa-user fa-fw"></i> <span class="">Users</span></a>
            </li>
            <li class="nav-item w-100">
                <a asp-controller="Workers" asp-action="Index" class="nav-link pl-0"><i class="fa fa-user fa-fw"></i> <span class="">Workers</span></a>
            </li>
            <li class="nav-item w-100">
                <a asp-controller="WorkLogs" asp-action="Index" class="nav-link pl-0"><i class="fa fa-list fa-fw"></i> <span class="">Work logs</span></a>
            </li>
            <li class="nav-item w-100">
                <a asp-controller="Worker" asp-action="WorkLogs" class="nav-link pl-0"><i class="fa fa-list fa-fw"></i> <span class="">My Work</span></a>
            </li>
        </ul>
    </nav>
</div>

LogAppWebCore/Views/Shared/_TopNavBar.cshtml
<header class="w-100">
    <nav class="navbar navbar-dark navbar-expand-sm bg-dark">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">LogAppWebCore</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="News" class="nav-link">News</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Contact" class="nav-link">Contact</a>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")

                <hr class="d-sm-none" />
                <ul class="flex-md-column navbar-nav w-100 justify-content-between d-sm-none">

                    <li class="nav-item w-100">
                        <a href="#submenu1Top" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle nav-link pl-0"><i class="fa fa-heart-o fa-fw"></i> <span class="">Home</span></a>
                        <ul class="collapse list-unstyled" id="submenu1Top">
                            <li>
                                <a class="nav-link" href="#">Home 1</a>
                            </li>
                            <li>
                                <a class="nav-link" href="#">Home 2</a>
                            </li>
                            <li>
                                <a class="nav-link" href="#">Home 3</a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item w-100">
                        <a class="nav-link pl-0" href="#"><i class="fa fa-heart-o fa-fw"></i> <span class="">Link</span></a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="nav-link pl-0" href="#"><i class="fa fa-book fa-fw"></i> <span class="">Link</span></a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="nav-link pl-0" href="#"><i class="fa fa-heart fa-fw"></i> <span class="">Link</span></a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="nav-link pl-0" href="#"><i class="fa fa-star fa-fw"></i> <span class="">Link</span></a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="nav-link pl-0" href="#"><i class="fa fa-list fa-fw"></i> <span class="">Link</span></a>
                    </li>
                </ul>
            </div>
    </nav>
</header>